#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 31 00:48:03 +03 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim histogram_equalizer_tb_behav -key {Behavioral:sim_1:Functional:histogram_equalizer_tb} -tclbatch histogram_equalizer_tb.tcl -view /home/burak/Desktop/histogram_equalizer/final_hist_eqaulizer/histogram_equalizer_tb_behav.wcfg -log simulate.log"
xsim histogram_equalizer_tb_behav -key {Behavioral:sim_1:Functional:histogram_equalizer_tb} -tclbatch histogram_equalizer_tb.tcl -view /home/burak/Desktop/histogram_equalizer/final_hist_eqaulizer/histogram_equalizer_tb_behav.wcfg -log simulate.log

